services:
  - type: web
    name: bme528-app
    runtime: python
    plan: free
    autoDeploy: true

    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
      python manage.py collectstatic --noinput

    startCommand: python manage.py migrate --noinput && gunicorn bme_gui.wsgi:application

    envVars:
      - key: PYTHON_VERSION
        value: "3.8.2"
      - key: DJANGO_SETTINGS_MODULE
        value: bme_gui.settings
      - key: DEBUG
        value: "False"
      # Option A: let Render create a strong secret for you
      - key: SECRET_KEY
        generateValue: true
